# Scraping NBA Data from basketball-reference

In the first part of this project, I will scrape MVP, all players and teams data from basketball reference using **beautiful soup** and **selenium**.

In [50]:
!pip3 install requests

Requirement already satisfied: requests in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (2.29.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from requests) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from requests) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from requests) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from requests) (2023.5.7)

### Getting MVP data from 1973-2023

In [72]:
# I scraped the data ten years at a time.
# You get blocked for an hour if accessing more than twenty pages a minute.
years = list(range(1973,2024))

In [64]:
# url of the website.
url_start = "https://www.basketball-reference.com/awards/awards_{}.html"

In [65]:
# scraping the webpage and stroing it into an html.
import requests
for year in years:
    url = url_start.format(year)
    data = requests.get(url)
    
    with open("mvp/{}.html".format(year), "w+") as f:
        f.write(data.text)

In [66]:
from bs4 import BeautifulSoup
import pandas as pd

In [67]:
# opening one html file and parsing the data into a dataframe.
with open("mvp/1991.html") as f:
    page = f.read()
soup = BeautifulSoup(page, "html.parser")
soup.find('tr', class_ = "over_header").decompose()
mvp_table = soup.find_all(id="mvp")
mvp_1991 = pd.read_html(str(mvp_table))[0]
mvp_1991

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,37.0,31.5,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321
1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,37.1,19.4,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251
2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,37.7,25.6,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264
3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,37.3,27.6,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258
4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,40.3,29.0,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225
5,6,Clyde Drexler,28,POR,1.0,75.0,960,0.078,82,34.8,21.5,6.7,6.0,1.8,0.7,0.482,0.319,0.794,12.4,0.209
6,7,Kevin Johnson,24,PHO,0.0,32.0,960,0.033,77,36.0,22.2,3.5,10.1,2.1,0.1,0.516,0.205,0.843,12.7,0.220
7,8,Dominique Wilkins,31,ATL,0.0,29.0,960,0.030,81,38.0,25.9,9.0,3.3,1.5,0.8,0.470,0.341,0.829,11.4,0.177
8,9T,Larry Bird,34,BOS,0.0,25.0,960,0.026,60,38.0,19.4,8.5,7.2,1.8,1.0,0.454,0.389,0.891,6.6,0.140
9,9T,Terry Porter,27,POR,0.0,25.0,960,0.026,81,32.9,17.0,3.5,8.0,2.0,0.1,0.515,0.415,0.823,13.0,0.235
10,11,Patrick Ewing,28,NYK,0.0,20.0,960,0.021,81,38.3,26.6,11.2,3.0,1.0,3.2,0.514,0.000,0.745,10.0,0.155
11,12,John Stockton,28,UTA,0.0,15.0,960,0.016,82,37.8,17.2,2.9,14.2,2.9,0.2,0.507,0.345,0.836,14.0,0.217
12,13,Isiah Thomas,29,DET,0.0,11.0,960,0.011,48,34.5,16.2,3.3,9.3,1.6,0.2,0.435,0.292,0.782,3.4,0.098
13,14,Robert Parish,37,BOS,0.0,10.0,960,0.010,81,30.1,14.9,10.6,0.8,0.8,1.3,0.598,0.000,0.767,10.0,0.198
14,15,Joe Dumars,27,DET,0.0,8.0,960,0.008,80,38.1,20.4,2.3,5.5,1.1,0.1,0.481,0.311,0.890,9.9,0.155
15,16,Bernard King,34,WSB,0.0,7.0,960,0.007,64,37.5,28.4,5.0,4.6,0.9,0.3,0.472,0.216,0.790,3.5,0.070
16,17,Kenny Smith,25,HOU,0.0,5.0,960,0.005,78,34.6,17.7,2.1,7.1,1.4,0.1,0.520,0.363,0.844,9.0,0.161
17,18,Hakeem Olajuwon,28,HOU,0.0,4.0,960,0.004,56,36.8,21.2,13.8,2.3,2.2,3.9,0.508,0.000,0.769,8.6,0.201
18,19T,Tim Hardaway,24,GSW,0.0,1.0,960,0.001,82,39.2,22.9,4.0,9.7,2.6,0.1,0.476,0.385,0.803,9.9,0.148
19,19T,Kevin McHale,33,BOS,0.0,1.0,960,0.001,68,30.4,18.4,7.1,1.9,0.4,2.1,0.553,0.405,0.829,7.9,0.182

In [104]:
# combining all the tables into one dataframe.
dfs = []
years = list(range(1980,2023))
for year in years:
    with open("mvp/{}.html".format(year)) as f:
        page = f.read()
        
    soup = BeautifulSoup(page, "html.parser")
    soup.find('tr', class_ = "over_header").decompose()
    mvp_table = soup.find_all(id="mvp")[0]
    mvp_df = pd.read_html(str(mvp_table))[0]
    mvp_df["Year"] = year
    dfs.append(mvp_df)

In [105]:
mvps = pd.concat(dfs)
mvps.head()

,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,MP,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,Year
0,1,Kareem Abdul-Jabbar,32,LAL,147.0,147.0,221,0.665,82,38.3,...,10.8,4.5,1.0,3.4,0.604,0.000,0.765,14.8,0.227,1980
1,2,Julius Erving,29,PHI,31.5,31.5,221,0.143,78,36.1,...,7.4,4.6,2.2,1.8,0.519,0.200,0.787,12.5,0.213,1980
2,3,George Gervin,27,SAS,19.0,19.0,221,0.086,78,37.6,...,5.2,2.6,1.4,1.0,0.528,0.314,0.852,10.6,0.173,1980
3,4,Larry Bird,23,BOS,15.0,15.0,221,0.068,82,36.0,...,10.4,4.5,1.7,0.6,0.474,0.406,0.836,11.2,0.182,1980
4,5T,Tiny Archibald,31,BOS,2.0,2.0,221,0.009,80,35.8,...,2.5,8.4,1.3,0.1,0.482,0.222,0.830,8.9,0.148,1980

In [106]:
mvps.to_csv("mvps.csv")

### Getting all players data.

In [107]:
player_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_per_game.html"

url = player_stats_url.format(1991)
data = requests.get(url)
with open("player/1991.html", "w+") as f:
    f.write(data.text)

In [108]:
!pip install selenium

Requirement already satisfied: selenium in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (4.11.2)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from selenium) (0.22.2)
Requirement already satisfied: trio-websocket~=0.9 in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from selenium) (0.10.3)
Requirement already satisfied: certifi>=2021.10.8 in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from selenium) (2023.5.7)
Requirement already satisfied: attrs>=20.1.0 in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sortedcontainers in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sniffio in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: exceptiongroup in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from trio-websocket~=0.9->selenium) (1.1.2)
Requirement already satisfied: wsproto>=0.14 in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /Users/ellietripathi/anaconda3/lib/python3.11/site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [109]:
from selenium import webdriver

In [110]:
driver = webdriver.Chrome()

In [111]:
import time

year = 1991
url = player_stats_url.format(year)

driver.get(url)
driver.execute_script("window.scrollTo(1,10000)")
time.sleep(2)

html = driver.page_source

In [112]:
with open("player/{}.html".format(year), "w+") as f:
    f.write(html)

In [116]:
# getting data 10 years at a time.
years = list(range(2006,2024))
for year in years:
    url = player_stats_url.format(year)

    driver.get(url)
    driver.execute_script("window.scrollTo(1,10000)")
    time.sleep(2)

    html = driver.page_source
    with open("player/{}.html".format(year), "w+") as f:
        f.write(html)

In [117]:
years = list(range(1980,2023))
dfs = []
for year in years:
    with open("player/{}.html".format(year)) as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    player_table = soup.find_all(id="per_game_stats")[0]
    player_df = pd.read_html(str(player_table))[0]
    player_df["Year"] = year
    dfs.append(player_df)

In [118]:
players = pd.concat(dfs)
players.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Kareem Abdul-Jabbar*,C,32,LAL,82,NaN,38.3,10.2,16.9,...,2.3,8.5,10.8,4.5,1.0,3.4,3.6,2.6,24.8,1980
1,2,Tom Abernethy,PF,25,GSW,67,NaN,18.2,2.3,4.7,...,0.9,1.9,2.9,1.3,0.5,0.2,0.6,1.8,5.4,1980
2,3,Alvan Adams,C,25,PHO,75,NaN,28.9,6.2,11.7,...,2.1,6.0,8.1,4.3,1.4,0.7,2.9,3.2,14.9,1980
3,4,Tiny Archibald*,PG,31,BOS,80,80,35.8,4.8,9.9,...,0.7,1.7,2.5,8.4,1.3,0.1,3.0,2.7,14.1,1980
4,5,Dennis Awtrey,C,31,CHI,26,NaN,21.5,1.0,2.3,...,1.1,3.3,4.4,1.5,0.5,0.6,1.0,2.5,3.3,1980

In [119]:
players.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,1,Kareem Abdul-Jabbar*,C,32,LAL,82,NaN,38.3,10.2,16.9,...,2.3,8.5,10.8,4.5,1.0,3.4,3.6,2.6,24.8,1980
1,2,Tom Abernethy,PF,25,GSW,67,NaN,18.2,2.3,4.7,...,0.9,1.9,2.9,1.3,0.5,0.2,0.6,1.8,5.4,1980
2,3,Alvan Adams,C,25,PHO,75,NaN,28.9,6.2,11.7,...,2.1,6.0,8.1,4.3,1.4,0.7,2.9,3.2,14.9,1980
3,4,Tiny Archibald*,PG,31,BOS,80,80,35.8,4.8,9.9,...,0.7,1.7,2.5,8.4,1.3,0.1,3.0,2.7,14.1,1980
4,5,Dennis Awtrey,C,31,CHI,26,NaN,21.5,1.0,2.3,...,1.1,3.3,4.4,1.5,0.5,0.6,1.0,2.5,3.3,1980

In [120]:
players.to_csv("players.csv")

### Getting team data.

In [124]:
team_stats_url = "https://www.basketball-reference.com/leagues/NBA_{}_standings.html"
years = list(range(2006,2024))
for year in years:

    url = team_stats_url.format(year)

    data = requests.get(url)

    with open("team/{}.html".format(year), "w+") as f:
        f.write(data.text)

In [125]:
# scraping two tables and combining the data together.
years = list(range(1980,2023))
dfs = []
for year in years:
    with open("team/{}.html".format(year)) as f:
        page = f.read()
    
    soup = BeautifulSoup(page, 'html.parser')
    soup.find('tr', class_="thead").decompose()
    e_table = soup.find_all(id="divs_standings_E")[0]
    e_df = pd.read_html(str(e_table))[0]
    e_df["Year"] = year
    e_df["Team"] = e_df["Eastern Conference"]
    del e_df["Eastern Conference"]
    dfs.append(e_df)
    
    w_table = soup.find_all(id="divs_standings_W")[0]
    w_df = pd.read_html(str(w_table))[0]
    w_df["Year"] = year
    w_df["Team"] = w_df["Western Conference"]
    del w_df["Western Conference"]
    dfs.append(w_df)

In [127]:
teams = pd.concat(dfs)
teams.head()

    W   L  W/L%    GB   PS/G   PA/G    SRS  Year                 Team
0  61  21  .744     —  113.5  105.7   7.37  1980      Boston Celtics*
1  59  23  .720   2.0  109.1  104.9   4.04  1980  Philadelphia 76ers*
2  39  43  .476  22.0  107.0  109.5  -2.27  1980  Washington Bullets*
3  39  43  .476  22.0  114.0  115.1  -0.96  1980      New York Knicks
4  34  48  .415  27.0  108.3  109.5  -0.98  1980      New Jersey Nets

In [128]:
teams.to_csv("teams.csv")